# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""USGS US Topo 7.5-minute quads: which a region needs, and how each is
verified.  D-068.

A quad is one 7.5 x 7.5 minute map sheet, published by USGS (public domain)
as a GeoTIFF of the whole page, collar included, at
``<bucket>/StagedProducts/Maps/USTopo/GeoTIFF/<ST>/<stem>_<date>_TM_geo.tif``.
Which quads exist, their bounding boxes, sizes and S3 ETags are carried in
the catalog as ``catalog/data/ustopo-quads.txt``, generated by
``scripts/gen_ustopo_index.py`` from USGS's ``ustopo_current.csv`` and a
listing of the bucket, so the plan needs no network to know which quads a
region needs.

A region's quads are those whose bounding box overlaps a 1/8-degree cell
its Geofabrik outline touches (:func:`hammunition.copernicus.squares_touching`
at ``per_degree=8``). Most quads sit exactly on that grid; 6,638 of the
65,240 (Alaska, oversized and off-grid sheets, measured 2026-09-29) do not,
which is why the index carries each box as decimals.

Each quad is verified against the ETag the index carries, re-asked with a
``HEAD`` at plan time. A single-part upload's ETag is its MD5; a multipart
one, ``<hex>-<parts>``, is the MD5 of its parts' MD5s, reproduced by trying
each whole-MiB part size that splits the object into that many parts
(:func:`etag_matches`). Neither is a sha256 Hammunition measured, and the
plan says so quad by quad, in the Copernicus wording (:data:`UNPINNED`).

Pure apart from the injected probe.
"""

from __future__ import annotations

import math
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

from . import s3etag
from .copernicus import UNPINNED, Ring, S3Probe, TileProbe, squares_touching
from .resolution import CatalogueMiss, ResolutionContext
from .s3etag import MIB, etag_matches, part_sizes

__all__ = [
    "BUCKET",
    "CELLS_PER_DEGREE",
    "INDEX_REMEDY",
    "MIB",
    "PREFIX",
    "UNPINNED",
    "Quad",
    "QuadIndex",
    "UstopoError",
    "bucket_probe",
    "check_quad",
    "etag_matches",
    "load_index",
    "parse_etag",
    "parse_index",
    "parse_row",
    "part_sizes",
    "render_row",
]

BUCKET = "https://prd-tnm.s3.amazonaws.com"
PREFIX = "StagedProducts/Maps/USTopo/GeoTIFF/"
SUFFIX = "_TM_geo.tif"
CELLS_PER_DEGREE = 8
INDEX_REMEDY = "scripts/gen_ustopo_index.py --fetch regenerates the carried index"
#: What the index carries after the box, size and ETag: ``<ST>/<stem>_<date>``.
PATH = re.compile(r"([A-Z]{2})/([A-Za-z0-9_.()'\-]+)_(\d{8})")
_NUMBER = r"(-?\d{1,3}(?:\.\d{1,9})?)"
LINE = re.compile(rf"{_NUMBER} {_NUMBER} {_NUMBER} {_NUMBER} (\d{{1,12}}) (\S+) (\S+)")
_EPSILON = 1e-9


class UstopoError(Exception):
    """An index, a quad or a checksum could not be read or verified."""


@dataclass(frozen=True)
class Quad:
    """One quad of the carried index."""

    south: float
    west: float
    north: float
    east: float
    size: int
    etag: str
    path: str
    """``<ST>/<stem>_<date>``, the object key without its prefix and suffix."""

    @property
    def name(self) -> str:
        """``<stem>_<date>``: the installed file's name without ``.tif``."""
        return self.path.split("/", 1)[1]

    @property
    def state(self) -> str:
        return self.path.split("/", 1)[0]

    @property
    def edition(self) -> str:
        """The date in the object's name, ``YYYYMMDD``."""
        return self.name.rsplit("_", 1)[1]

    @property
    def key(self) -> str:
        return f"{PREFIX}{self.path}{SUFFIX}"

    @property
    def url(self) -> str:
        return f"{BUCKET}/{self.key}"

    @property
    def verified_by(self) -> str:
        return UNPINNED


def parse_etag(etag: str) -> tuple[str, int | None]:
    """(hex, parts) of an S3 ETag (:func:`hammunition.s3etag.parse_etag`),
    refused as a :class:`UstopoError`."""
    try:
        return s3etag.parse_etag(etag)
    except s3etag.EtagError as exc:
        raise UstopoError(str(exc)) from exc


def render_row(quad: Quad) -> str:
    """*quad* as one index row, the form :func:`parse_row` reads back."""
    return (
        f"{_degrees(quad.south)} {_degrees(quad.west)} {_degrees(quad.north)} "
        f"{_degrees(quad.east)} {quad.size} {quad.etag} {quad.path}"
    )


def _degrees(value: float) -> str:
    text = f"{value:.7f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def parse_row(line: str, number: int = 1) -> Quad:
    """One index row as a :class:`Quad`, or a refusal naming line *number*."""
    match = LINE.fullmatch(line)
    if match is None:
        raise UstopoError(f"line {number} is not an index row: {line[:100]!r}")
    south, west, north, east = (float(match.group(i)) for i in range(1, 5))
    size, etag, path = int(match.group(5)), match.group(6), match.group(7)
    if PATH.fullmatch(path) is None:
        raise UstopoError(f"line {number}: {path!r} is not <ST>/<name>_<YYYYMMDD>")
    parse_etag(etag)
    if not (-90 <= south < north <= 90 and -180 <= west < east <= 180):
        raise UstopoError(f"line {number}: the box {south} {west} {north} {east} is not a box")
    if size <= 0:
        raise UstopoError(f"line {number}: size {size} is not a positive number of bytes")
    return Quad(south, west, north, east, size, etag, path)


class Boxed(Protocol):
    """Anything with a box in degrees: a US Topo or an FSTopo quad."""

    @property
    def south(self) -> float: ...
    @property
    def west(self) -> float: ...
    @property
    def north(self) -> float: ...
    @property
    def east(self) -> float: ...


def boxed_cells(quad: Boxed) -> Iterable[tuple[int, int]]:
    """The 1/8-degree cells *quad*'s box overlaps with some area."""
    return _cells(quad)


def _cells(quad: Boxed) -> Iterable[tuple[int, int]]:
    """The 1/8-degree cells *quad*'s box overlaps with some area."""
    rows = range(
        math.floor(quad.south * CELLS_PER_DEGREE + _EPSILON),
        math.ceil(quad.north * CELLS_PER_DEGREE - _EPSILON),
    )
    columns = range(
        math.floor(quad.west * CELLS_PER_DEGREE + _EPSILON),
        math.ceil(quad.east * CELLS_PER_DEGREE - _EPSILON),
    )
    for row in rows:
        for column in columns:
            yield row, column


@dataclass(frozen=True)
class QuadIndex:
    """The carried index, looked up by cell."""

    quads: tuple[Quad, ...]
    by_cell: dict[tuple[int, int], tuple[Quad, ...]] = field(
        default_factory=dict, compare=False, repr=False
    )

    @classmethod
    def of(cls, quads: Sequence[Quad]) -> QuadIndex:
        cells: dict[tuple[int, int], list[Quad]] = {}
        for quad in quads:
            for cell in _cells(quad):
                cells.setdefault(cell, []).append(quad)
        return cls(tuple(quads), {cell: tuple(found) for cell, found in cells.items()})

    @staticmethod
    def touched(outer: Sequence[Ring], holes: Sequence[Ring] = ()) -> frozenset[tuple[int, int]]:
        """The 1/8-degree cells an outline touches."""
        return squares_touching(outer, holes, per_degree=CELLS_PER_DEGREE)

    def select(self, outer: Sequence[Ring], holes: Sequence[Ring] = ()) -> tuple[Quad, ...]:
        """Every quad whose box overlaps a cell the outline touches, by path."""
        found: dict[str, Quad] = {}
        for cell in self.touched(outer, holes):
            for quad in self.by_cell.get(cell, ()):
                found[quad.path] = quad
        return tuple(found[path] for path in sorted(found))

    def by_path(self) -> dict[str, Quad]:
        return {quad.path: quad for quad in self.quads}


def parse_index(text: str) -> QuadIndex:
    """The carried index: one quad a line, ``#`` comments and blanks skipped.

    An empty or comment-only index is refused, never read as "no quad
    anywhere": a truncated file would otherwise take every region's topo
    sheets away with no warning (the Copernicus list's rule, D-061)."""
    quads: list[Quad] = []
    seen: set[str] = set()
    for number, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        quad = parse_row(line, number)
        if quad.path in seen:
            raise UstopoError(f"line {number} carries {quad.path} a second time")
        seen.add(quad.path)
        quads.append(quad)
    if not quads:
        raise UstopoError(
            "the US Topo index names no quads; an empty or comment-only "
            f"catalog/data/ustopo-quads.txt would otherwise select nothing anywhere. "
            f"{INDEX_REMEDY}"
        )
    return QuadIndex.of(quads)


def load_index(path: Path) -> QuadIndex:
    try:
        text = path.read_text()
    except OSError as exc:
        raise UstopoError(
            f"the US Topo index {path} cannot be read ({exc.strerror or exc}); it is "
            f"carried in the catalog, and {INDEX_REMEDY}"
        ) from exc
    return parse_index(text)


def bucket_probe() -> S3Probe:
    """The real probe for sheets: a ``HEAD`` to :data:`BUCKET` and nowhere else."""
    return S3Probe(bucket=BUCKET)


def _check_quad_online(quad: Quad, probe: TileProbe) -> None:
    """Refuse *quad* unless the bucket still serves it as the index says:
    status 200, the same size and the same ETag. A changed object is not
    fetched against a stale checksum."""
    status, size, etag = probe.head(quad.url)
    if status != 200:
        raise UstopoError(
            f"{quad.name}: {quad.url} answered HTTP {status}, not 200; {INDEX_REMEDY}"
        )
    if size != quad.size or (etag or "").strip().strip('"') != quad.etag:
        raise UstopoError(
            f"{quad.name}: the bucket now reports {size} bytes and ETag {etag!r}, where "
            f"the carried index has {quad.size} and {quad.etag!r}; the object changed "
            f"since the index was built, so it is not fetched against the old "
            f"checksum. {INDEX_REMEDY}"
        )


def _recorded_quad(quad: Quad, context: ResolutionContext, unit: str) -> None:
    """The Bunker's record for *quad*, compared with the carried index.

    The index (the repository's own copy) is the independent side: the
    record's publisher size, multipart-capable ETag and URL must equal it, so
    the Bunker cannot move what the download is checked against. The bytes are
    checked later, by the fetch (``Fetcher.fetch_etag`` against ``quad.etag``
    and ``quad.size``), not here."""
    context.require_payload(unit, quad.path, size=quad.size)
    row = context.require_payload(unit, quad.path, publisher_digest=quad.etag)
    if row.publisher_url != quad.url:
        raise CatalogueMiss(f"{unit}/{quad.path}: publisher URL disagrees with the index")
    if row.publisher_size is not None and row.publisher_size != quad.size:
        raise CatalogueMiss(f"{unit}/{quad.path}: publisher size disagrees with the index")


def check_quad(
    quad: Quad,
    probe: TileProbe,
    *,
    context: ResolutionContext | None = None,
    unit: str | None = None,
) -> None:
    """:func:`_check_quad_online`, or with a *context* the Bunker's record when
    the bucket cannot be asked. Nothing on *quad* is replaced: the download is
    still checked against the index's ETag and size."""
    if context is None:
        return _check_quad_online(quad, probe)
    if unit is None:
        raise UstopoError("US Topo catalogue check needs its resolved unit name")
    return context.choose(
        unit,
        quad.path,
        lambda: _check_quad_online(quad, probe),
        lambda: _recorded_quad(quad, context, unit),
    )
